[package]
name = "Divination"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.4"
anyhow = { version = "1.0.66", features = ["backtrace"] }
serde_json = "1.0.117"
regex = "1.10.4"
toml = "0.8.13"
serde = { version = "1.0.201", features = ["derive"] }
cargo_metadata = "0.18.1"
