// Import types
#pragma rsuse OsString = std::ffi::OsString
#pragma rsuse VecOsString = std::vec::Vec<std::ffi::OsString>
#pragma rsuse PopenConfig = subprocess::PopenConfig
#pragma rsuse Popen = subprocess::Popen
#pragma rsuse PopenResult = subprocess::Result<subprocess::Popen>
#pragma rsuse ExitStatusResult = subprocess::Result<subprocess::ExitStatus>
// Import methods (theoretically only needed for non-generic languages like C)
#pragma rsfn VecOsString_new = std::vec::Vec::<std::ffi::OsString>::new
#pragma rsfn VecOsString_push = std::vec::Vec::<std::ffi::OsString>::push
#pragma rsfn VecOsString_as_slice = std::vec::Vec::<std::ffi::OsString>::as_slice
#pragma rsfn PopenConfig_default = subprocess::PopenConfig::default
#pragma rsfn Popen_wait = subprocess::Popen::wait
#pragma rsfn PopenResult_is_ok = subprocess::Result::<subprocess::Popen>::is_ok
#pragma rsfn PopenResult_unwrap = subprocess::Result::<subprocess::Popen>::unwrap
#pragma rsfn ExitStatusResult_is_ok = subprocess::Result::<subprocess::ExitStatus>::is_ok
#pragma rsfn OsString_drop = std::ffi::OsString::drop
#pragma rsfn VecOsString_drop = std::vec::Vec::<std::ffi::OsString>::drop
#pragma rsfn Popen_drop = subprocess::Popen::drop
#pragma rsfn PopenResult_drop = subprocess::Result::<subprocess::Popen>::drop
#pragma rsfn ExitStatusResult_drop = subprocess::Result::<subprocess::ExitStatus>::drop
#pragma rsfn OsString_from_str = std::ffi::OsString::from(&str)
#pragma rsfn Popen_create = subprocess::Popen::create(&[std::ffi::OsString], _)

// Import the header generated by the Makefile invoking the tool
#include "rust_deps/rust_deps.h"

#include <stdio.h>

int main() {
  // let mut argv = Vec::new();
  VecOsString argv = VecOsString_new();
  // argv.push(OsString::from("/bin/cat"));
  VecOsString_push(&argv, OsString_from_str(rust_StrFromCStr("/bin/cat")));
  // argv.push(OsString::from("hello.txt"));
  VecOsString_push(&argv, OsString_from_str(rust_StrFromCStr("hello.txt")));

  // let create_result = Popen::create(&argv, PopenConfig::default());
  PopenResult create_result =
      Popen_create(
          VecOsString_as_slice(&argv),
          PopenConfig_default());

  // let mut process = 
  //   match create_result {
  //     Err(_) => panic!("Failed to open subprocess!"),
  //     Ok(process) => process
  //   };
  if (!PopenResult_is_ok(&create_result)) {
    printf("Failed to open subprocess!\n");
    // Drops implicit in Rust
    PopenResult_drop(create_result);
    VecOsString_drop(argv);
    return 1;
  }
  Popen process = PopenResult_unwrap(create_result);

  // let wait_result = process.wait();
  // if !wait_result.is_ok() {
  //   panic!("Failed to wait on subprocess!");
  // }
  ExitStatusResult wait_result = Popen_wait(&process);
  if (!ExitStatusResult_is_ok(&wait_result)) {
    printf("Failed to wait on subprocess!\n");
    // Drops implicit in Rust
    ExitStatusResult_drop(wait_result);
    Popen_drop(process);
    PopenResult_drop(create_result);
    VecOsString_drop(argv);
    return 1;
  }

  // println!("Success!");
  printf("Success!\n");

  // Drops implicit in Rust
  ExitStatusResult_drop(wait_result);
  Popen_drop(process);
  PopenResult_drop(create_result);
  VecOsString_drop(argv);
  return 0;
}
