[package]
name = "rust_deps"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
lto = true
codegen-units = 1
panic = "abort"
opt-level = "z"  # Optimize for size.

[features]
default = []
capi = ["libc"]

[dependencies]
libc = { version = "0.2", optional = true }
static_assertions = "1.1.0"
subprocess = "0.2.9"
regex = "1.10.4"

[dev-dependencies]
inline-c = "0.1"

[build-dependencies]
cargo_metadata = "0.14"
subprocess = "0.2.9"

[package.metadata.capi.header]
subdirectory = "rust_deps"

[package.metadata.capi.pkg_config]
strip_include_path_components = 1

[package.metadata.capi.library]
rustflags = "-Cpanic=abort"
name = "example-project"

#[package.metadata.capi.install.include]
#asset = [{from = "include/file.h", to = "otherplace" }]
#generated = [{from = "include/other_file.h", to = "otherplace" }]
